stages:         
  - build
  - deploy

build-job:      
  stage: build
  script:
    - cd /home/ubuntu/projects
    - sudo docker-compose build

deploy-job:     
  stage: deploy
  script:
    - cd /home/ubuntu/projects
    - sudo docker-compose up -d
