export const urls = {
  main: "/",
  signup: "/signup",
  login: "/login",
  serverError: "/error",
  explore: "/explore",
  myPage: "/mypage",
  resetPassword: "/reset-password",
  confirmEmail: "/confirm-email",
  forgetPassword: "/forget-password",
  forgetPasswordInfo: "/forget-password-info",
  editProfile: "/edit-profile",
  notFound: "/not-found",
  createPost: "/create-post",
  viewPost: "/view-post",
};
